//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnWinInterop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Service
    {
        public int ID { get; set; }
        public int Order_ID { get; set; }
        public int Service_Code { get; set; }
        public Nullable<double> Result { get; set; }
        public Nullable<System.DateTime> Finished_Date { get; set; }
        public bool Accepted { get; set; }
        public string Status { get; set; }
        public string Analyzer { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.TimeSpan> Lead_Time { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Service Service { get; set; }
    }
}
